#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Dixmod\Command\{Import, Show};
use Symfony\Component\Console\Application;

$app = new Application('YoutubeOtusStatistics', 1.0);
$app->add(new Import());
$app->add(new Show());

$app->run();
